IMAGE_NAME="aquaeye-ai"
IMAGE_TAG="v3.0.0"
ENVIRONMENT="PROD"
HTTP_SERVER_PORT=5000
EXPRESS_APP_PORT=4000

if [ $ENVIRONMENT = "PROD" ]
then
  REACT_CLIENT_PORT=80
elif [ $ENVIRONMENT = "DEV" ]
then
  REACT_CLIENT_PORT=3000
else
  echo "WARNING: Undefined ENVIRONMENT"
fi
